version: '3.4'
services:
  db:
    restart: unless-stopped
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  decide_redis:
    restart: unless-stopped
    image: redis:6-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data
  nginx:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: tecnologia@exploradoresdemadrid.org
      ENVSUBST_VARS: FQDN
      FQDN: "*.exploradoresdemadrid.org"
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - web
      - salamandra
  web:
    restart: unless-stopped
    image: exploradoresdemadrid/decide:master
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      DEVISE_JWT_SECRET_KEY: ${DEVISE_JWT_SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      POSTGRES_HOST: db
      REDIS_URL: redis://decide_redis:6379/0
      API_TOKEN: ${DECIDE_API_TOKEN}
      SMOKETEST_EMAIL: ${DECIDE_SMOKETEST_EMAIL}
      SMOKETEST_PASSWORD: ${DECIDE_SMOKETEST_PASSWORD}
      DECIDE_SMTP_USERNAME: ${DECIDE_SMTP_USERNAME}
      DECIDE_SMTP_PASSWORD: ${DECIDE_SMTP_PASSWORD}
      DECIDE_SMTP_ADDRESS: ${DECIDE_SMTP_ADDRESS}
      DECIDE_HOST: ${DECIDE_HOST}
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    expose:
      - "3000"
    depends_on:
      - db
      - decide_redis
      - migration
    volumes:
      - logs:/decide/log
  migration:
    image: exploradoresdemadrid/decide:master
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      POSTGRES_HOST: db
    command: "bundle exec rake db:create db:migrate"
    depends_on:
      - db
  workers:
    restart: unless-stopped
    image: exploradoresdemadrid/decide:master
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      POSTGRES_HOST: db
      REDIS_URL: redis://decide_redis:6379/0
      DECIDE_SMTP_USERNAME: ${DECIDE_SMTP_USERNAME}
      DECIDE_SMTP_PASSWORD: ${DECIDE_SMTP_PASSWORD}
      DECIDE_SMTP_ADDRESS: ${DECIDE_SMTP_ADDRESS}
      DECIDE_HOST: ${DECIDE_HOST}
    command: "bundle exec sidekiq"
    depends_on:
      - db
      - decide_redis
  sorting-hat-web:
    restart: unless-stopped
    image: exploradoresdemadrid/sorting_hat:master
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      POSTGRES_HOST: db
      REDIS_URL: redis://decide_redis:6379/1
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    expose:
      - "3000"
    depends_on:
      - db
      - decide_redis
      - sorting-hat-migration
    volumes:
      - logs:/sorting-hat/log
  sorting-hat-migration:
    image: exploradoresdemadrid/sorting_hat:master
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      POSTGRES_HOST: db
    command: "bundle exec rake db:create db:migrate"
    depends_on:
      - db
  sorting-hat-workers:
    restart: unless-stopped
    image: exploradoresdemadrid/sorting_hat:master
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      POSTGRES_HOST: db
      REDIS_URL: redis://decide_redis:6379/1
    command: "bundle exec sidekiq -c 1"
    depends_on:
      - db
      - decide_redis
  salamandra:
    restart: unless-stopped
    image: exploradoresdemadrid/salamandra:master
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "80"
    depends_on:
      - db
    volumes:
      - /home/ubuntu/salamandra/modules:/var/www/html/modules
      - /home/ubuntu/salamandra/profiles:/var/www/html/profiles
      - /home/ubuntu/salamandra/themes:/var/www/html/themes
      - /home/ubuntu/salamandra/sites:/var/www/html/sites
      - /home/ubuntu/salamandra/private_files:/var/www/salamandra_private
volumes:
  pgdata:
  letsencrypt:
  redis-data:
  logs: