version: '3.1'

services:
  wordpress:
    image: wordpress:5.5.3
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
  docker-web:
    image: exploradoresdemadrid/docker-web:master
    restart: always
    expose:
      - "80"
  nginx:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: tecnologia@exploradoresdemadrid.org
      ENVSUBST_VARS: FQDN
      FQDN: "*.exploradoresdemadrid.org"
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - wordpress
      - docker-web

volumes:
  wordpress:
  db: