version: '3.1'

services:
  nginx:
    restart: always
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: mayn13@gmail.com
      ENVSUBST_VARS: FQDN
      FQDN: "*.www.exploradoresdemadrid.org"
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - wordpress
  wordpress:
    image: wordpress:5.7.1
    restart: always
    expose:
      - "80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress:/var/www/html
  wordpress_copy:
    image: wordpress:5.7.1
    restart: always
    expose:
      - "80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER_2}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD_2}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME_2}
    volumes:
      - wordpress_2:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  wordpress_2:
  db:
  letsencrypt: